# Generated by Django 3.2.25 on 2025-03-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='manufacturing',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان ١'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان ٢'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.BooleanField(default=False, verbose_name='عميل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='payment_method',
            field=models.CharField(choices=[('فورى', 'فورى'), ('شيكات', 'شيكات'), ('دفعات', 'دفعات')], max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=11, verbose_name='الهاتف ١'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='الهاتف ٢'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='price_list',
            field=models.PositiveIntegerField(verbose_name='قائمة الأسعار'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='province',
            field=models.CharField(max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='vendor',
            field=models.BooleanField(default=False, verbose_name='مورد'),
        ),
    ]
