# Generated by Django 3.2.25 on 2025-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_auto_20250517_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersafeassignment',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Safe'),
        ),
    ]
