# Generated by Django 3.2.25 on 2025-05-15 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector Name')),
                ('sector_number', models.IntegerField(blank=True, null=True, verbose_name='Sector Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('requested_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Requested Quantity')),
                ('unit', models.CharField(choices=[('قطعة', 'Piece'), ('طقم', 'Set'), ('كرتونة', 'Carton'), ('كيلو جرام', 'Kilogram'), ('متر', 'Meter'), ('لتر', 'Liter'), ('علبة', 'Can/Box'), ('دستة', 'Dozen')], max_length=50, verbose_name='Unit')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spare_parts_photos/', verbose_name='Photo')),
                ('ordered_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ordered Quantity')),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Received Quantity')),
                ('status', models.CharField(choices=[('New', 'New Request'), ('Ordered', 'Ordered and Waiting for Delivery'), ('Received', 'Received')], default='New', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spare_parts.category', verbose_name='Category')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_spare_part_requests', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Spare Part Request',
                'verbose_name_plural': 'Spare Part Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
